import type { Metadata } from 'next'
import { DM_Sans, Figtree, Inter, Lora } from 'next/font/google'
import './globals.css'
import Header from './components/layout/header'
import Footer from './components/layout/footer'

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dmsans",
  display: "swap",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  display: "swap",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pilih weight ikut suka
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: 'Asuroo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${dmSans.variable} ${lora.variable}`}>
      <body className="font-dmsans">
        <Header />
        {children}
         <Footer />
        </body>
    </html>
  )
}
